# docker-compose.yml
version: "3"
services:
  napcat:
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    ports:
      - 3000:3000
      - 6099:6099
    volumes:
      - ./runtime/napcat/QQ:/app/.config/QQ
      - ./runtime/napcat/config:/app/napcat/config
      - ./runtime/napcat/plugins:/app/napcat/plugins
      - ./runtime/napcat/shared:/app/shared
    container_name: napcat
    restart: always
    image: mlikiowa/napcat-docker:latest